version: "3.3"
x-metadata:
  replicas: 1
  name: alpine
  labels:
    k1: v1
    k2: v2
services:
  alpine:
    restart: always
    image: alpine:3.9.4
    hostname: alpine
    entrypoint: tail -f /etc/hostname